sudo: required
services:
  - docker
before_install:
  - docker build -t danielbilic/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true danielbilic/docker-react npm run test -- --coverage
